openapi: 3.0.0
info:
  title: 'Example of using interfaces in swagger-php'
  description: 'Shows how to define operations in interfaces'
  contact:
    email: examples@swagger.io
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: 'Dummy Server'
paths:
  '/products/{id}':
    get:
      tags:
        - Products
      description: 'Get product'
      operationId: 'UsingInterfaces\ProductController::getProduct'
      parameters:
        -
          name: id
          in: path
          description: 'Product id'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      title: 'Product model'
      allOf:
        -
          $ref: '#/components/schemas/ProductInterface'
        -
          properties:
            id:
              description: 'The unique identifier of a product in our catalog.'
              type: integer
              format: int64
              example: 1
    ProductInterface:
      properties:
        name:
          description: 'The product name.'
          example: toaster
      type: object
tags:
  -
    name: Products
    description: 'Product stuff'
