openapi: 3.0.0
info:
  title: 'Example of using traits in swagger-php'
  version: 1.0.0
paths:
  '/entities/{id}':
    delete:
      tags:
        - Entities
      operationId: 341f63c1bb8a9c0c0392b112a967a05f
      parameters:
        -
          name: id
          in: path
          description: 'ID of entity to delete'
          required: true
          schema:
            type: string
      responses:
        default:
          description: 'successful operation'
  '/products/{product_id}':
    get:
      tags:
        - Products
      operationId: 1395fb672d283f343885d77e3a1ce8a5
      parameters:
        -
          name: product_id
          in: path
          description: 'ID of product to return'
          required: true
          schema:
            type: string
      responses:
        default:
          description: 'successful operation'
components:
  schemas:
    BellsAndWhistles:
      title: 'Bells and Whistles trait'
      allOf:
        -
          properties:
            plating:
              description: 'The plating.'
              example: gold
        -
          $ref: '#/components/schemas/Bells'
        -
          $ref: '#/components/schemas/Whistles'
    CustomName/Blink:
      title: 'Blink trait'
      properties:
        frequency:
          description: 'The frequency.'
          example: 1
      type: object
    Colour:
      title: 'Colour trait'
      properties:
        colour:
          description: 'The colour.'
          example: red
      type: object
    Bells:
      title: 'Bells trait'
      properties:
        bell:
          description: 'The bell (clashes with Product::bell).'
          example: chime
      type: object
    Whistles:
      title: 'Whistles trait'
      properties:
        whistle:
          description: 'The bell.'
          example: 'bone whistle'
      type: object
    DeleteEntity:
      title: 'Delete entity trait'
    Product:
      title: 'Product model'
      allOf:
        -
          properties:
            id:
              description: 'The unique identifier of a product in our catalog.'
              type: integer
              format: int64
              example: 1
            bell:
              description: 'The product bell.'
              example: gong
        -
          $ref: '#/components/schemas/Colour'
        -
          $ref: '#/components/schemas/BellsAndWhistles'
    SimpleProduct:
      title: 'SimpleProduct model'
      allOf:
        -
          properties:
            id:
              description: 'The unique identifier of a simple product in our catalog.'
              type: integer
              format: int64
              example: 1
        -
          $ref: '#/components/schemas/Bells'
    TrickyProduct:
      title: 'TrickyProduct model'
      allOf:
        -
          properties:
            trick:
              description: 'The trick.'
              example: 'recite poem'
        -
          $ref: '#/components/schemas/SimpleProduct'
        -
          $ref: '#/components/schemas/CustomName~1Blink'
