openapi: 3.0.0
info:
  title: 'Example of using traits in swagger-php'
  description: 'Shows how traits can be used'
  contact:
    email: examples@swagger.io
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: 'Dummy Server'
paths:
  '/entities/{id}':
    delete:
      tags:
        - Entities
      description: 'Delete entity'
      operationId: 'UsingTraits\DeleteEntity::deleteEntity'
      parameters:
        -
          name: id
          in: path
          description: 'Entity id'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'successful operation'
  '/products/{product_id}':
    get:
      tags:
        - Products
      description: 'Get a product'
      operationId: 'UsingTraits\ProductController::getProduct'
      parameters:
        -
          name: product_id
          in: path
          description: 'Product id'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'successful operation'
components:
  schemas:
    BellsAndWhistles:
      title: 'Bells and Whistles trait'
    Blink:
      title: 'Blink trait'
    Colour:
      title: 'Colour trait'
    Bells:
      title: 'Bells trait'
    Whistles:
      title: 'Whistles trait'
    DeleteEntity:
      title: 'Delete entity trait'
    Product:
      title: 'Product model'
      properties:
        colour:
          description: 'The colour.'
          example: red
        plating:
          description: 'The plating.'
          example: gold
        bell:
          description: 'The bell.'
          example: chime
        whistle:
          description: 'The bell.'
          example: 'bone whistle'
        id:
          description: 'The unique identifier of a product in our catalog.'
          type: integer
          format: int64
          example: 1
      type: object
    SimpleProduct:
      title: 'SimpleProduct model'
      properties:
        bell:
          description: 'The bell.'
          example: chime
        id:
          description: 'The unique identifier of a simple product in our catalog.'
          type: integer
          format: int64
          example: 1
      type: object
    TrickyProduct:
      allOf:
        -
          $ref: '#/components/schemas/SimpleProduct'
        -
          title: 'TrickyProduct model'
          properties:
            bell:
              description: 'The bell.'
              example: chime
            frequency:
              description: 'The frequency.'
              example: 1
            trick:
              description: 'The trick.'
              example: 'recite poem'
          type: object
tags:
  -
    name: Products
    description: 'Product stuff'
  -
    name: Entities
    description: 'Entity stuff'
