openapi: 3.1.0
info:
  title: 'Example API'
  description: 'Example info'
  contact:
    name: 'Swagger API Team'
  version: '1.0'
servers:
  - url: 'https://example.localhost'
    description: 'API server'
