<?php declare(strict_types=1);

/*
 * Generated by `php tools/rector-map.php` - do not edit.
 *
 * Classic `OpenApi\Attributes` => spec `OpenApi\Spec`, for the classes that map one to one.
 * Renaming the class is stage one of the migration and changes no emitted document: the
 * historic argument names survive on the spec attributes as deprecated aliases until 8.0.
 *
 * Two classic attributes are absent because they need a restructure rather than a rename:
 * - `Attributes\Query` becomes OpenApi\Spec\Operation with method: 'query' - the HTTP QUERY method is OpenAPI 3.2 and spec has no Operation\Query shortcut yet.
 * - `Attributes\Webhook` becomes a webhook: argument on an operation attribute - no longer an attribute of its own.
 */

return [
    \OpenApi\Attributes\AdditionalProperties::class => \OpenApi\Spec\Schema\AdditionalProperties::class,
    \OpenApi\Attributes\Attachable::class => \OpenApi\Spec\Attachable::class,
    \OpenApi\Attributes\Components::class => \OpenApi\Spec\Components::class,
    \OpenApi\Attributes\Contact::class => \OpenApi\Spec\Contact::class,
    \OpenApi\Attributes\CookieParameter::class => \OpenApi\Spec\Parameter\Cookie::class,
    \OpenApi\Attributes\Delete::class => \OpenApi\Spec\Operation\Delete::class,
    \OpenApi\Attributes\Discriminator::class => \OpenApi\Spec\Discriminator::class,
    \OpenApi\Attributes\Encoding::class => \OpenApi\Spec\Encoding::class,
    \OpenApi\Attributes\Examples::class => \OpenApi\Spec\Example::class,
    \OpenApi\Attributes\ExternalDocumentation::class => \OpenApi\Spec\ExternalDocumentation::class,
    \OpenApi\Attributes\Flow::class => \OpenApi\Spec\Flow::class,
    \OpenApi\Attributes\Get::class => \OpenApi\Spec\Operation\Get::class,
    \OpenApi\Attributes\Head::class => \OpenApi\Spec\Operation\Head::class,
    \OpenApi\Attributes\Header::class => \OpenApi\Spec\Header::class,
    \OpenApi\Attributes\HeaderParameter::class => \OpenApi\Spec\Parameter\Header::class,
    \OpenApi\Attributes\Info::class => \OpenApi\Spec\Info::class,
    \OpenApi\Attributes\Items::class => \OpenApi\Spec\Schema\Items::class,
    \OpenApi\Attributes\JsonContent::class => \OpenApi\Spec\MediaType\Json::class,
    \OpenApi\Attributes\License::class => \OpenApi\Spec\License::class,
    \OpenApi\Attributes\Link::class => \OpenApi\Spec\Link::class,
    \OpenApi\Attributes\MediaType::class => \OpenApi\Spec\MediaType::class,
    \OpenApi\Attributes\OpenApi::class => \OpenApi\Spec\OpenApi::class,
    \OpenApi\Attributes\Options::class => \OpenApi\Spec\Operation\Options::class,
    \OpenApi\Attributes\Parameter::class => \OpenApi\Spec\Parameter::class,
    \OpenApi\Attributes\Patch::class => \OpenApi\Spec\Operation\Patch::class,
    \OpenApi\Attributes\PathItem::class => \OpenApi\Spec\PathItem::class,
    \OpenApi\Attributes\PathParameter::class => \OpenApi\Spec\Parameter\Path::class,
    \OpenApi\Attributes\Post::class => \OpenApi\Spec\Operation\Post::class,
    \OpenApi\Attributes\Property::class => \OpenApi\Spec\Property::class,
    \OpenApi\Attributes\Put::class => \OpenApi\Spec\Operation\Put::class,
    \OpenApi\Attributes\QueryParameter::class => \OpenApi\Spec\Parameter\Query::class,
    \OpenApi\Attributes\RequestBody::class => \OpenApi\Spec\RequestBody::class,
    \OpenApi\Attributes\Response::class => \OpenApi\Spec\Response::class,
    \OpenApi\Attributes\Schema::class => \OpenApi\Spec\Schema::class,
    \OpenApi\Attributes\SecurityScheme::class => \OpenApi\Spec\Security\Scheme::class,
    \OpenApi\Attributes\Server::class => \OpenApi\Spec\Server::class,
    \OpenApi\Attributes\ServerVariable::class => \OpenApi\Spec\ServerVariable::class,
    \OpenApi\Attributes\Tag::class => \OpenApi\Spec\Tag::class,
    \OpenApi\Attributes\Trace::class => \OpenApi\Spec\Operation\Trace::class,
    \OpenApi\Attributes\Xml::class => \OpenApi\Spec\Xml::class,
    \OpenApi\Attributes\XmlContent::class => \OpenApi\Spec\MediaType\Xml::class,
];
