openapi: 3.0.0
info:
  title: 'Nested schemas'
  description: 'An entity controller class.'
  version: 1.0.0
paths:
  'entity/{id}':
    get:
      tags:
        - api
      operationId: ba071babc56eee118c82b2278c55f6c7
      responses:
        default:
          description: 'successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActualModel'
components:
  schemas:
    ActualModel:
      type: object
      allOf:
        -
          $ref: '#/components/schemas/AlmostModel'
        -
          properties:
            actual:
              type: string
            soClose:
              type: string
    AlmostModel:
      type: object
      allOf:
        -
          $ref: '#/components/schemas/BaseModel'
        -
          properties:
            almost:
              type: string
            intermediate:
              type: string
    BaseModel:
      properties:
        base:
          type: string
      type: object
