openapi: 3.1.0
paths:
  /api/secure/:
    get:
      summary: 'Requires authentication'
      security:
        -
          api_key: []
        -
          petstore_auth:
            - 'write:pets'
            - 'read:pets'
