<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-25 at 19:30:24.
 */
set_include_path(
    get_include_path() .
    ':/Users/zircote/zend/Swagger-PHP/library'.
    ':/Users/zircote/zend/Swagger-PHP/sample'
);
require_once 'Zircote/Swagger.php';
require_once 'Zircote/Swagger/Resource.php';
require_once 'Zend/Json.php';
class Zircote_Swagger_ResourceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Zircote_Swagger_Resource
     */
    protected $resource;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Zircote_Swagger_Resource::buildResource
     * @todo   Implement testBuildResource().
     */
    public function testBuildResource()
    {
//         echo Zend_Json::prettyPrint(Zend_Json::encode(($this->resource->results))), PHP_EOL;
//         foreach ($this->resource->apis as $api) {
//             echo Zend_Json::prettyPrint(Zend_Json::encode(($api->results)));
//         }
        $path = realpath(dirname(dirname(dirname(__DIR__))) . '/sample');
        $swagger = Zircote_Swagger::discover($path);

        echo $swagger->getResource('http://org.local/v1');

        echo PHP_EOL,PHP_EOL;

        echo $swagger->getApi('http://org.local/v1', '/leadresponder');
//         print_r($swagger->models->results);
    }

}
