<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-03-25 at 19:30:24.
 */
require_once 'Swagger.php';
require_once 'Swagger/Resource.php';
class Swagger_ResourceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Swagger_Resource
     */
    protected $resource;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Swagger_Resource::buildResource
     * @todo   Implement testBuildResource().
     */
    public function testBuildResource()
    {
        $path = realpath(dirname(dirname(dirname(__DIR__))) . '/sample');
        $swagger = Swagger::discover($path);

        echo $swagger->getResource('http://org.local/v1');

        echo PHP_EOL,PHP_EOL;

        echo $swagger->getApi('http://org.local/v1', '/leadresponder');
//         print_r($swagger->models->results);
    }

}
