openapi: 3.0.0
info:
  title: 'Testing annotations from bugreports'
  description: 'Misc examples'
  contact:
    email: bugs@swagger.php
  version: 1.0.0
servers:
  -
    url: '{schema}://host.dev'
    description: 'OpenApi server details'
    variables:
      schema:
        enum:
          - https
          - http
        default: https
paths:
  /api/endpoint:
    get:
      tags:
        - api
        - other
      description: 'Api endpoint'
      operationId: endpoint
      parameters:
        -
          name: filter
          in: query
          content:
            application/json:
              schema:
                properties:
                  type: { type: string }
                  color: { type: string }
                type: object
      responses:
        '200':
          description: Success
tags:
  -
    name: api
    description: 'All API endpoints'
  -
    name: other
    description: 'Other tag'
