openapi: 3.0.0
info:
  title: 'Testing annotations from bugreports'
  description: "NOTE:\nThis sentence is on a new line"
  contact:
    name: 'Swagger API Team'
  version: 1.0.0
servers:
  -
    url: '{schema}://host.dev'
    description: 'OpenApi parameters'
    variables:
      schema:
        enum:
          - https
          - http
        default: https
paths:
  /api/endpoint:
    get:
      tags:
        - endpoints
      summary: 'An API endpoint.'
      description: 'An endpoint'
      operationId: endpoint
      parameters:
        -
          name: filter
          in: query
          content:
            application/json:
              schema:
                properties:
                  type: { type: string }
                  color: { type: string }
                type: object
      responses:
        '200':
          $ref: '#/components/responses/200'
      security:
        -
          bearerAuth: []
  /api/anotherendpoint:
    get:
      tags:
        - endpoints
      summary: 'Another API endpoint.'
      description: 'Another endpoint'
      operationId: anotherendpoints
      parameters:
        -
          name: 'things[]'
          in: query
          description: 'A list of things.'
          required: false
          schema:
            type: array
            items:
              type: integer
      responses:
        '200':
          $ref: '#/components/responses/200'
      security:
        -
          bearerAuth: []
components:
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            properties:
              name:
                description: demo
                type: integer
            type: object
          examples:
            '200':
              summary: ''
              value:
                name: 1
            '300':
              summary: ''
              value:
                name: 1
            '400':
              summary: ''
              value:
                name: 1
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  -
    bearerAuth: []
tags:
  -
    name: endpoints
