<?php declare(strict_types=1);

/*
 * Generates `rector/set/classic-to-spec-classes.php`, the classic -> spec class map the
 * migration set is built from.
 *
 *     php tools/rector-map.php
 *
 * The map is generated rather than hand-written so it cannot drift from the two attribute
 * namespaces. Matching on the short class name alone is wrong -- `Query` is the HTTP QUERY
 * operation in classic and a query *parameter* in spec -- so anything the short name cannot
 * resolve is declared here and anything left over is reported rather than guessed.
 */

require __DIR__ . '/../vendor/autoload.php';

/** Classic short name => spec relative name, where short-name matching is wrong or impossible. */
const EXPLICIT = [
    'CookieParameter' => 'Parameter\Cookie',
    'HeaderParameter' => 'Parameter\Header',
    'PathParameter' => 'Parameter\Path',
    'QueryParameter' => 'Parameter\Query',
    'JsonContent' => 'MediaType\Json',
    'XmlContent' => 'MediaType\Xml',
    'Examples' => 'Example',
    'SecurityScheme' => 'Security\Scheme',
];

/** Classic names that need a restructure, not a rename; a rule of their own handles each. */
const RESTRUCTURE = [
    'Query' => 'OpenApi\Spec\Operation with method: \'query\' - the HTTP QUERY method is OpenAPI 3.2 and spec has no Operation\Query shortcut yet',
    'Webhook' => 'a webhook: argument on an operation attribute - no longer an attribute of its own',
];

function classesIn(string $dir, string $ns): array
{
    $out = [];
    foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir)) as $file) {
        if (!$file->isFile() || 'php' !== $file->getExtension()) {
            continue;
        }
        $rel = str_replace('/', '\\', substr($file->getPathname(), strlen($dir) + 1, -4));
        $class = $ns . '\\' . $rel;
        if (!class_exists($class)) {
            continue;
        }
        $rc = new \ReflectionClass($class);
        if ($rc->isAbstract() || $rc->isInterface() || $rc->isTrait()) {
            continue;
        }
        $out[$rel] = $class;
    }
    ksort($out);

    return $out;
}

$root = dirname(__DIR__);
$classic = classesIn($root . '/src/Attributes', 'OpenApi\Attributes');
$spec = classesIn($root . '/src/Spec', 'OpenApi\Spec');

$byShort = [];
foreach ($spec as $rel => $class) {
    $byShort[substr(strrchr('\\' . $rel, '\\'), 1)][$rel] = $class;
}

$map = [];
$unresolved = [];
foreach ($classic as $rel => $class) {
    if (isset(RESTRUCTURE[$rel])) {
        continue;
    }
    $target = EXPLICIT[$rel] ?? null;
    if (null === $target) {
        $candidates = $byShort[substr(strrchr('\\' . $rel, '\\'), 1)] ?? [];
        if (!$candidates) {
            $unresolved[] = $rel;
            continue;
        }
        $target = isset($candidates[$rel]) ? $rel : array_key_first($candidates);
    }
    if (!isset($spec[$target])) {
        $unresolved[] = $rel . ' -> ' . $target;
        continue;
    }
    $map[$class] = $spec[$target];
}

if ($unresolved) {
    fwrite(STDERR, 'unresolved: ' . implode(', ', $unresolved) . "\n");

    exit(1);
}

$lines = [];
foreach ($map as $from => $to) {
    $lines[] = sprintf('    %s::class => %s::class,', '\\' . $from, '\\' . $to);
}
$notes = implode("\n", array_map(
    fn (string $name, string $why) => sprintf(' * - `Attributes\%s` becomes %s.', $name, $why),
    array_keys(RESTRUCTURE),
    RESTRUCTURE
));

$out = <<<PHP
<?php declare(strict_types=1);

/*
 * Generated by `php tools/rector-map.php` - do not edit.
 *
 * Classic `OpenApi\Attributes` => spec `OpenApi\Spec`, for the classes that map one to one.
 * Renaming the class is stage one of the migration and changes no emitted document: the
 * historic argument names survive on the spec attributes as deprecated aliases until 8.0.
 *
 * Two classic attributes are absent because they need a restructure rather than a rename:
{$notes}
 */

return [
PHP . "\n" . implode("\n", $lines) . "\n];\n";

file_put_contents($root . '/rector/set/classic-to-spec-classes.php', $out);
printf("wrote %d class renames\n", count($map));
