openapi: 3.0.0
info:
  title: 'Webhook Example'
  version: 1.0.0
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
      type: object
