openapi: 3.0.0
info:
  title: 'Example for response examples value'
  description: 'Example for response examples value'
  contact:
    email: examples@swagger.php
  version: 1.0.0
servers:
  -
    url: '{schema}://host.dev'
    description: 'OpenApi server details'
    variables:
      schema:
        enum:
          - https
          - http
        default: https
paths:
  /users:
    post:
      tags:
        - user
      summary: 'Adds a new user'
      description: 'Creates a new user in the database'
      operationId: add_user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                name:
                  type: string
              type: object
              example:
                id: '10'
                name: 'Jessica Smith'
      responses:
        '200':
          description: OK
tags:
  -
    name: user
    description: 'All user related endpoints'
