name: gh-pages

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      dryrun:
        description: Dry run
        type: boolean
        required: false

concurrency:
  group: gh-pages
  cancel-in-progress: true

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: ramsey/composer-install@v4
        with:
          dependency-versions: 'highest'

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      - name: Install vitepress and deps
        run: cd docs && npm ci

      - name: Build site
        run: composer docs:build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
          dry_run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dryrun == 'true' }}
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
